In [2]:
import numpy as np
import random as r

### Metode Power

In [4]:
# constants
RAND_LOW = -16
RAND_HIGH = 16
ITERATION = 100
SIZE = 3

a = np.zeros((SIZE,SIZE))
b = np.zeros(SIZE)

for i in range(SIZE):
    b[i] = r.randint(RAND_LOW, RAND_HIGH)
    # for j in range(SIZE):
    #     a[i,j] = r.randint(RAND_LOW,RAND_HIGH)

# a = np.array([[1,1,0],[1,0,1],[0,1,1]])
a = np.array([[2,-3,0],[2,-5,0],[0,0,3]])

print("known:")
print("a=", a)
print("b=", b)

def mult(a,b):
    n = len(a)
    c = np.zeros(n)
    for i in range(n):
        for j in range(n):
            c[i]+=a[i,j]*b[j]
    # print("a*b=",c)
    return c

def div_with_max(c,d):
    n = len(c)
    e = np.zeros(n)
    for i in range(n):
        e[i]=c[i]/d
    return e

# print(mult(a,b))
# print(max(mult(a,b)))

def power(a,b):
    A = np.copy(a); B = np.copy(b)
    for i in range(ITERATION):
        c = mult(A,B)
        d = max(abs(c))
        # print("d=",d)
        B = div_with_max(c,d)
    return d,B

d,b=power(a,b)
print("\ndominant eigenvalue=", d)
print("dominant eigenvector=", b)

known:
a= [[ 2 -3  0]
 [ 2 -5  0]
 [ 0  0  3]]
b= [-13.  12. -11.]

dominant eigenvalue= 4.0
dominant eigenvector= [ 5.00000000e-01  1.00000000e+00 -1.79996041e-13]


### Metode Dekomposisi QR

In [5]:
import math

# a = np.zeros((SIZE,SIZE))

# for i in range(SIZE):
#     for j in range(SIZE):
#         a[i,j] = r.randint(RAND_LOW,RAND_HIGH)

SIZE = 3
# a = np.array([[5,-2],[7,-4]])
# a = np.array([[1,1,0],[1,0,1],[0,1,1]])
# a = np.array([[2,1,-1],[1,0,2],[2,-1,3]])
# a = np.array([[4,7,11],[-16,11,-9],[-5,16,3]])
a = np.array([[2,-3,0],[2,-5,0],[0,0,3]])


print("known:")
print("a=", a)

# A = QR; find Q using gram schmidt; find R using row operation

def norm(vec):
    norm = 0
    for i in range(SIZE):
        norm += math.pow(vec[i],2)
    return norm

def cur_vec(a, i):
    vec = a[0:SIZE,i]
    return vec

def gs(a):
    # initialise final e vector
    e = np.zeros((SIZE,SIZE))

    # k = 1
    # grab current vector
    vec = cur_vec(a,0) # print("v=",vec) <-- current vector
    # print("vec=",vec)
    # calculate norm
    temp = norm(vec)
    # find e_1
    for i in range(SIZE):
        e[i,0]=vec[i]/math.sqrt(temp)
    # print("e_1=",e)

    # print("norm=",temp)
    # print("e=",e)

    # k > 1
    for k in range(1,SIZE):
        vec = cur_vec(a,k)
        temp_res = 0
        for l in range(0,k):
            vec_e = cur_vec(e,l)
            # print("vec_e=",vec_e)
            # print("dot=",np.dot(vec,vec_e))
            temp_res += np.dot(vec,vec_e)*vec_e
            # print("dot * vec_e=",temp_res)
        # print("vec=",vec)
        numerator = vec - temp_res
        # print(numerator)
        # print("debug_norm=",math.sqrt(norm(temp_res)))
        for m in range(SIZE):
            # print("m=",m)
            e[m,k]=numerator[m]/math.sqrt(norm(numerator))
        # print("e=",e)
        
    return e

# 00 01 02
# 10 11 12
# 20 21 22

def row_op(a):
    A = np.copy(a)
    n=len(A)
    # OBE
    # standard case
    for i in range(n):
        for j in range(i+1, n):
            k = -1 * A[j,i] / A[i,i]
            A[j,i:n] = k * A[i,i:n] + A[j,i:n]
    return A

def qr_decomp(a):
    # R = row_op(a)
    # A = np.matmul(Q,R)

    A = np.copy(a)
    n=len(A)

    # k = 1,2,3,...
    for i in range(ITERATION):
        Q = gs(A)
        R = np.matmul(Q.T, A)
        A = np.matmul(R,Q)
        # print("A=",A)   

    res = np.zeros(n)
    for i in range(n):
        res[i] = A[i,i]

    return res

    # print("res=",A*np.eye(3))
    # print("Q=",Q)
    # print("R=",R) 

print("eigenvalues=",qr_decomp(np.array([
        [2, 1, 2],
        [1, 3, 4],
        [2, 2, 1]
    ])))

# print(row_op(a))

known:
a= [[ 2 -3  0]
 [ 2 -5  0]
 [ 0  0  3]]
eigenvalues= [ 6.02911192 -0.46268247  0.43357055]
