# Persamaan Linear
Eliminasi Gauss, Dekomposisi LU, Metode Choleski

In [8]:
import numpy as np

size = int(input("size=?"))

A = np.zeros((size,size)).astype(float)
B = np.zeros(size).astype(float)

msg = "input {} digits delim=space -> A".format(size**2)
raw_A = input(msg)
split_A = raw_A.split()
k = 0
for i in range(size):
    for j in range(size):
        A[i,j]=split_A[k]
        k+=1

msg = "input {} digits delim=space -> B".format(size)
raw_B = input(msg)
split_B = raw_B.split()
for i in range(size):
    B[i] = split_B[i]

# create copies
D = np.zeros((size,size)).astype(float)
E = np.zeros(size).astype(float)
F = np.zeros((size,size)).astype(float)
G = np.zeros(size).astype(float)

for i in range(size):
    for j in range(size):
        D[i,j] = A[i,j]; F[i,j] = A[i,j]

for i in range(size):
    E[i] = B[i]; G[i] = B[i]

Eliminasi Gauss

In [3]:
def gauss_elimination(A, B):
    n = len(B)
    x = np.zeros(n).astype(float)

    # OBE
    # standard case
    for i in range(n):
        for j in range(i+1, n):
            k = -1 * A[j,i] / A[i,i]
            A[j,i:n] = k * A[i,i:n] + A[j,i:n]
            B[j] = k * B[i] + B[j]
    
    # back-sub
    for i in range(n-1,-1,-1):
        x[i] = (B[i] - np.dot(A[i,i+1:n],x[i+1:n])) / A[i,i]
    return x

In [4]:
alist = [[1, 1, 1], [1, 2, -1], [2, 1, 2]]
blist = [6, 2, 10]
a = np.array(alist)
b = np.array(blist)

gauss_elimination(a, b)

array([1., 2., 3.])

Dekomposisi LU

In [11]:
def lu(A, B):
    n = len(A)
    U = np.zeros((n,n)).astype(float)
    L = np.eye(n).astype(float)

    # U = A
    for i in range(n):
        for j in range(n):
            U[i,j]=A[i,j]

    # mencari U dengan OBE (standard case)
    for i in range(n):
        for j in range(i+1, n):
            k = -1 * U[j,i] / U[i,i]
            U[j,i:n] = k * U[i,i:n] + U[j,i:n]
            print(U)

    print("Looking for L")
    # mencari L dari A = LU
    for i in range(1,n):
        for j in range(0,i):
            L[i,j] = (A[i,j] - np.dot(L[i,0:n], U[0:n,j])) / U[j,j]
            print(L)

    # mencari Ly = B --> y = L aug B
    y = gauss_elimination(L,B)
    
    # mencari Ux = y --> x = U aug y
    x = gauss_elimination(U,y)

    return x

In [12]:
# Nomor 1
a3 = [[4, 3, -1], [-2, -4, 5], [1, 2, 6]]
b3 = [9, 2, 16]

x3 = lu(np.array(a3), np.array(b3))
print(f"a = {a3}\nb = {b3}\nx = {x3}")

[[ 4.   3.  -1. ]
 [ 0.  -2.5  4.5]
 [ 1.   2.   6. ]]
[[ 4.    3.   -1.  ]
 [ 0.   -2.5   4.5 ]
 [ 0.    1.25  6.25]]
[[ 4.   3.  -1. ]
 [ 0.  -2.5  4.5]
 [ 0.   0.   8.5]]
Looking for L
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 0.   0.   1. ]]
[[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.25  0.    1.  ]]
[[ 1.    0.    0.  ]
 [-0.5   1.    0.  ]
 [ 0.25 -0.5   1.  ]]
a = [[4, 3, -1], [-2, -4, 5], [1, 2, 6]]
b = [9, 2, 16]
x = [1.97941176 0.98823529 1.88235294]


Cholesky

In [6]:
import math

def cholesky(A, B):
    L = choleskyInit(A)
    return choleskySolve(L, B)

def choleskyInit(A):
    n = len(A)
    print("A: ", a)
    for k in range(n):
        try:
            A[k,k] = math.sqrt(A[k,k] - np.dot(A[k,0:k],A[k,0:k]))
        except ValueError:
            print("Matriks tidak dapat diselesaikan dengan metode ini")
            return A
        for i in range(k+1,n):
            if A[k,k] != 0.0:
                A[i,k] = (A[i,k] - np.dot(A[i,0:k],A[k,0:k]))/A[k,k]
    
    for k in range(1,n): A[0:k,k] = 0.0

    return A

def choleskySolve(L, B):
    n = len(B)

    # Mencari Ly = B
    for k in range(n):
        if L[k,k] != 0.0:
            B[k] = (B[k] - np.dot(L[k,0:k],B[0:k]))/L[k,k]

    # Mencari Ux = y dengan U = L^T
    for k in range(n-1,-1,-1):
        if L[k,k] != 0.0:
            B[k] = (B[k] - np.dot(L[k+1:n,k],B[k+1:n]))/L[k,k]
    
    return B

In [9]:
print("eliminiasi gauss =",gauss_elimination(A, B))
print("dekomposisi LU =",lu(D, E))
print("choleski =",cholesky(F, G))
a5 = [[1, 3, 5], [3, 13, 23], [5, 23, 42]]
print(choleskyInit(np.array(a5)))

eliminiasi gauss = [nan nan nan]
dekomposisi LU = [nan nan nan]
Matriks tidak dapat diselesaikan dengan metode ini
choleski = [ 2.81481481 -0.16049383 -0.02469136]
[[1 0 0]
 [3 2 0]
 [5 4 1]]


C:\Users\RAYHAN EGAR\AppData\Local\Temp\ipykernel_4332\1100457268.py:15: RuntimeWarning: invalid value encountered in double_scalars
  x[i] = (B[i] - np.dot(A[i,i+1:n],x[i+1:n])) / A[i,i]
