Ini teks

In [2]:
print ('halo')

halo


In [3]:
p = 1
q = 2
r = p+q
print (r)

3


In [4]:
a = 1
b = 2.3
c = a + b
print (c)

3.3


# A. Struktur data


1.   List
      - mutable
      - their elements are usually homogeneous and are accessed by iterating over the list.
2.   Tuple
      -  immutable
      - usually contain a heterogeneous sequence of elements

1.   Set
      - store an unordered collection with no duplicate elements
      - upport the mathematical operations like union, intersection, difference, and symmetric difference

2.   Dictionaries
    
    - elements are stored without order
    - To get access to a dictionary, we need to use the key of the element - dictionary[key]







In [5]:
#1. List

list_1 = [1, 2, 3]
list_1

[1, 2, 3]

In [6]:
list_2 = ['Hello', 'World']
list_2

['Hello', 'World']

In [7]:
list_3 = [1, 2, 3, 'Apple', 'orange']
list_3

[1, 2, 3, 'Apple', 'orange']

In [8]:
list_4 = [list_1, list_2, list_3]
list_4

[[1, 2, 3], ['Hello', 'World'], [1, 2, 3, 'Apple', 'orange']]

In [9]:
list_3[2] #Get the 3rd element in list_3
list_3[4]


'orange'

In [10]:
list_3[:4] # Get the first 3 elements in list_3

[1, 2, 3, 'Apple']

In [11]:
list_3[-1] #Get the last element in list_3

'orange'

In [12]:
len(list_3)

5

In [13]:
listx = list_1 + list_2  # Add list_1 and list_2 to one list.
listx

[1, 2, 3, 'Hello', 'World']

In [14]:
list_1.append(4)
list_1

[1, 2, 3, 4]

In [15]:
list_1.insert(2,'center')
list_1

[1, 2, 'center', 3, 4]

In [16]:
#2. Tuples

tuple_1 = (1, 2, 3, 2)
tuple_1

(1, 2, 3, 2)

In [17]:
len(tuple_1)

4

In [18]:
tuple_1.count(2)

2

In [19]:
#3. Sets

set_1 = set([1, 2, 2, 3, 2, 1, 2])
set_1

{1, 2, 3}

In [20]:
set_2 = set((2, 4, 6, 5, 2))
set_2

{2, 4, 5, 6}

In [21]:
print(set_1)
print(set_2)

{1, 2, 3}
{2, 4, 5, 6}


In [22]:
set_1.union(set_2)

{1, 2, 3, 4, 5, 6}

In [23]:
set_1.intersection(set_2)

{2}

In [24]:
set_1.issubset({1, 2, 3, 3, 4, 5})

True

In [25]:
#4. Dictionaries

dict_1 = {'apple':3, 'oragne':4, 'pear':2}
dict_1

{'apple': 3, 'oragne': 4, 'pear': 2}

In [26]:
dict_1['apple']

3

In [27]:
dict_1.keys()

dict_keys(['apple', 'oragne', 'pear'])

In [28]:
dict_1.values()

dict_values([3, 4, 2])

In [29]:
len(dict_1)

3

# 2. Numpy Arrays

Numpy is the most fundamental numerical computing module in Python.

##Few important features for Numpy :


*   a powerful N-dimensional array object
*   sophisticated (broadcasting) functions


*   tools for integrating C/C++ and Fortran code
*   useful linear algebra, Fourier transform, and random number capabilities

c:> pip install numpy










In [1]:
import numpy as np

Create the following arrays:

$$ x = \begin{pmatrix}
       1 & 4 & 3
       \end{pmatrix}
$$

$$
y  = \begin{pmatrix}
      1 & 4 & 3\\
      9 & 2 & 7
      \end{pmatrix}
$$


In [31]:
x = np.array([1,4,3])
x

array([1, 4, 3])

In [32]:
y = np.array([[1,4,3],[9,2,7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [33]:
y.shape  # Find the rows and, columns

(2, 3)

In [34]:
y.size # total size for array y

6

In [35]:
z = np.arange(1, 2000, 3) # Create an array z from 1 to 2000 with an increment 2.
z

array([   1,    4,    7,   10,   13,   16,   19,   22,   25,   28,   31,
         34,   37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
         67,   70,   73,   76,   79,   82,   85,   88,   91,   94,   97,
        100,  103,  106,  109,  112,  115,  118,  121,  124,  127,  130,
        133,  136,  139,  142,  145,  148,  151,  154,  157,  160,  163,
        166,  169,  172,  175,  178,  181,  184,  187,  190,  193,  196,
        199,  202,  205,  208,  211,  214,  217,  220,  223,  226,  229,
        232,  235,  238,  241,  244,  247,  250,  253,  256,  259,  262,
        265,  268,  271,  274,  277,  280,  283,  286,  289,  292,  295,
        298,  301,  304,  307,  310,  313,  316,  319,  322,  325,  328,
        331,  334,  337,  340,  343,  346,  349,  352,  355,  358,  361,
        364,  367,  370,  373,  376,  379,  382,  385,  388,  391,  394,
        397,  400,  403,  406,  409,  412,  415,  418,  421,  424,  427,
        430,  433,  436,  439,  442,  445,  448,  4

In [36]:
p = np.arange(0.5, 3, 0.1) # Generate an array with [0.5, 1, 1.5, 2, 2.5]
p

array([0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7,
       1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [37]:
q = np.linspace(3, 9, 10) # generate an array starting at 3, ending at 9, and containing 10 elements
q

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [38]:
q[1] # get the 2nd element of q


3.6666666666666665

In [39]:
q[5:] # get all the element after the 5nd element of q

array([6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

In [40]:
q[:3]

array([3.        , 3.66666667, 4.33333333])

In [41]:
q[-1] # get the last element of x

9.0

In [42]:
y

array([[1, 4, 3],
       [9, 2, 7]])

In [43]:
y[0, :] # Get the second row of array y.

array([1, 4, 3])

In [44]:
y[:, -1] # Get the last column of array y.

array([3, 7])

In [45]:
y[:,1]

array([4, 2])

In [46]:
y[:, 1] # Get the second column of array y.

array([4, 2])

In [47]:
y[:, [0, 2]]  #Get the first and third column of array y

array([[1, 3],
       [9, 7]])

In [48]:
np.zeros((3, 5)) # Generate a 3 by 5 array with all the as 0.


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
np.ones((5, 3)) #Generate a 5 by 3 array with all the element as 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###Excercise :
Make array

$$
  a = \begin{pmatrix}  
      1&2&3&4&5&6
      \end{pmatrix}
$$



In [50]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [51]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [52]:
a[3] = 7 # eassign the fourth element of a to 7
a

array([1, 2, 3, 7, 5, 6])

In [53]:
a[:3] = 1 #Reassign the first, second, and thrid elements to 1
a

array([1, 1, 1, 7, 5, 6])

In [54]:
a[2:] = 5
a

array([1, 1, 5, 5, 5, 5])

In [55]:
a[1:4] = [9, 8, 7] #Reassign the second, third, and fourth elements to 9, 8, and 7.
a

array([1, 9, 8, 7, 5, 5])

## Operational pada Matrix

$$
  A = \begin{pmatrix}
      2&-4\\
      -2&10       
      \end{pmatrix}
$$

$$
  B = \begin{pmatrix}
  1&2\\
  3&4
  \end{pmatrix}
$$

In [56]:
A = np.array([[2,-4],[-2,10]])
A


array([[ 2, -4],
       [-2, 10]])

In [57]:
B = np.array([[1,2],[3,4]])
B

array([[1, 2],
       [3, 4]])

In [58]:
C = A+B
C

array([[ 3, -2],
       [ 1, 14]])

In [59]:
C = A-B
C

array([[ 1, -6],
       [-5,  6]])

In [60]:
C = A**B
C

array([[    2,    16],
       [   -8, 10000]])

In [61]:
C = A*B
C

array([[ 2, -8],
       [-6, 40]])

In [62]:
A+2

array([[ 4, -2],
       [ 0, 12]])

In [63]:
A**2

array([[  4,  16],
       [  4, 100]])

In [64]:
A/2

array([[ 1., -2.],
       [-1.,  5.]])

#3. Multiplication in NumPy


In [65]:
import numpy as np
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,1,1], [0,1,0], [1,1,1]])
print("Matrix A is:\n",A)
print("Matrix A is:\n",B)
C = np.matmul(A,B)
print("Matrix multiplication of matrix A and B is:\n",C)
D = np.dot(A,B)
print("Matrix multiplication of matrix A and B is:\n",D)

Matrix A is:
 [[1 2 3]
 [4 5 6]]
Matrix A is:
 [[1 1 1]
 [0 1 0]
 [1 1 1]]
Matrix multiplication of matrix A and B is:
 [[ 4  6  4]
 [10 15 10]]
Matrix multiplication of matrix A and B is:
 [[ 4  6  4]
 [10 15 10]]


#4. Function

def function_name(argument_1, argument_2, ...):
    '''
    Descriptive String
    '''
    # comments about the statements
    function_statements
    
    return output_parameters (optional)



In [66]:
def tambah(a,b):
  return a+b

a = 5
b = 6
c = tambah(a,b)
print (c)

11


In [67]:
def fungsi1(a,b) :
  return a+b, a-b, a*b

a1 = 5
a2 = 6
b1,b2,b3 = fungsi1(a1,a2)
print ("%d + %d = %d" %(a1,a2,b1) )
print ("%d - %d = %d" %(a1,a2,b2) )
print ("%d * %d = %d" %(a1,a2,b3) )

5 + 6 = 11
5 - 6 = -1
5 * 6 = 30


In [68]:
def my_trig_sum(a, b):
    """
    function to demo return multiple
    author
    date
    """
    out1 = np.sin(a) + np.cos(b)
    out2 = np.sin(b) + np.cos(a)
    return out1, out2, [out1, out2]

c, d, e = my_trig_sum(2, 3)
print(f"c ={c}, d={d}, e={e}")

c =-0.0806950697747637, d=-0.2750268284872752, e=[-0.0806950697747637, -0.2750268284872752]


## Nested function

In [69]:
import numpy as np

def my_dist_xyz(x, y, z):
    """
    x, y, z are 2D coordinates contained in a tuple
    output:
    d - list, where
        d[0] is the distance between x and y
        d[1] is the distance between x and z
        d[2] is the distance between y and z
    """

    def my_dist(x, y):
        """
        subfunction for my_dist_xyz
        Output is the distance between x and y,
        computed using the distance formula
        """
        out = np.sqrt((x[0]-y[0])**2+(x[1]-y[1])**2)
        return out

    d0 = my_dist(x, y)
    d1 = my_dist(x, z)
    d2 = my_dist(y, z)

    return [d0, d1, d2]


d = my_dist_xyz((0, 0), (0, 1), (1, 1))
print(d)


[1.0, 1.4142135623730951, 1.0]


# Lambda Functions

   - function is just one line
   - a function that is defined without a name

   ***lambda arguments: expression***

In [70]:
square = lambda x: x**2

print(square(2))
print(square(5))

4
25


In [71]:
my_adder = lambda x, y: x + y

print(my_adder(2, 4))

6


In [72]:
sorted([(1, 2, 4), (2, 0, 2), (4, 1, 5)], key=lambda x: x[2])  # Sort [(1, 2, 4), (2, 0, 2), (4, 1, 5)] based on the 3nd item in the tuple

[(2, 0, 2), (1, 2, 4), (4, 1, 5)]

$$
    f(x,y,z) = x^y - z
$$

In [73]:
fn = lambda x,y, z: x**y - z



In [74]:
print ("%d^%d - %d = %d" %(2,3,6,fn(2,3,6)))

2^3 - 6 = 2


## Functions as Arguments to Functions

In [75]:
import numpy as np

def my_fun_plus_one(f, x):
    return f(x) + 1

print(my_fun_plus_one(np.sin, np.pi/2))
print(my_fun_plus_one(np.cos, np.pi/2))
print(my_fun_plus_one(np.sqrt, 25))

2.0
1.0
6.0


#5. Branching Statements

In [76]:
def assesment(score):
  if score >= 80:
    return "LULUS"
  else:
    return "GAGAL"

nilai1 = 81.5
print ("Nilai %.2f = %s" %(nilai1, assesment(nilai1)))

Nilai 81.50 = LULUS


## Ternary Operators

***expression_if_true if condition else expression_if_false***

In [77]:
is_student = True
person = 'student' if is_student else 'not student'
print(person)

student


In [78]:
hitung1 = lambda x, y : x**y
hitung2 = lambda x, y : y**x
hasil1 = lambda x, y : x if x > y else y
x = 10
y = 3
hasil2 = lambda x,y : hitung1(x,y) if x > y else hitung2(x,y)
print ("karena %d > %d maka hasil hitungnya %d" %(x, y, hasil1(x,y)))
print ("karena %d > %d maka hasil hitungnya %d" %(x, y, hasil2(x,y)))

karena 10 > 3 maka hasil hitungnya 10
karena 10 > 3 maka hasil hitungnya 1000


# Iteration

In [79]:
n = 0
for i in range(1, 4):
    print(i)
    n = n + i

print(n)

1
2
3
6


In [80]:
i = 0
n = 8

while n >= 1:
    n /= 2
    i += 1

print(f'n = {n}, i = {i}')

n = 0.5, i = 4


## Comprehensions

***[Output Input_sequence Conditions]***

In [81]:
x = range(5)
y = []

for i in x:
    y.append(i**2)
print(y)


[0, 1, 4, 9, 16]


In [82]:
y = [i**2 for i in x]
print(y)

[0, 1, 4, 9, 16]


In [83]:
y = [i**2 for i in x if i%2 == 0]
print(y)

[0, 4, 16]


In [84]:
y = [i + j for i in range(5) for j in range(2)]
print(y)

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5]
