# MN23_A2_LK3

### Ketua Kelompok
1. Rayhan Egar Sadtya Nugraha (225150201111014)

### Anggota Kelompok 
1. Hugo Alfedo Putra (225150201111013)
2. Arion Syemael Siahaan(225150207111060)

In [2]:
import numpy as np
import math

## Forward dan Backward Substitution

In [59]:
def forward_substitution(a, b):
    n = len(a)
    y = np.zeros(n).astype(float)

    y[0] = b[0]
    for i in range(1, n):
        sum_term = np.dot(a[i, 0:n], b[0:n])
        y[i] = (b[i] - sum_term) / a[i, i]
    
    return y

def backward_substitution(a, y):
    n = len(a)
    x = np.zeros(n).astype(float)

    for i in range (n-1, -1, -1):
        sum_term = np.dot(a[i, i+1:n], x[i+1:n])
        x[i] = (y[i] - sum_term) / a[i, i]

    return x


## Gauss Elimination Method

In [1]:
def gauss_elimination(a, b):

    n = len(b)
    x = np.zeros(n).astype(float)

    # Iterasi pivot row
    for j in range(n):

        # Iterasi modified row
        # Eliminasi gaussian
        for i in range(j+1, n):
            ratio = a[i, j] / a[j, j]
            a[i, j:n] = a[i, j:n] - ratio * a[j, j:n]
            b[i] = b[i] - ratio * b[j]

    # Back-substitution
    for i in range(n-1, -1, -1):
        sum_term = np.dot(a[i, i+1:n], x[i+1:n])
        x[i] = (b[i] - sum_term) / a[i, i]

    return x

### Latihan Gauss Elimination

In [3]:
# Nomor 1
a1 = [[1, 1, 1], [1, 2, -1], [2, 1, 2]]
b1 = [6, 2, 10]

x1 = gauss_elimination(np.array(a1), np.array(b1))
print(f"a = {a1}\nb = {b1}\nx = {x1}")

a = [[1, 1, 1], [1, 2, -1], [2, 1, 2]]
b = [6, 2, 10]
x = [1. 2. 3.]


In [62]:
# Nomor 2
a2 = [[2.51, 1.48, 4.53], [1.48, 0.93, -1.3], [2.68, 3.04, -1.48]]
b2 = [0.05, 1.03, -0.53]

x2 = gauss_elimination(np.array(a2), np.array(b2))
print(f"a = {a2}\nb = {b2}\nx = {x2}")

a = [[2.51, 1.48, 4.53], [1.48, 0.93, -1.3], [2.68, 3.04, -1.48]]
b = [0.05, 1.03, -0.53]
x = [ 1.4531001  -1.58919486 -0.27489467]


## LU Decomposition Method

In [4]:
def lu_decomposition(a, b):
    n = len(a)
    u = np.zeros_like(a).astype(float)
    l = np.eye(n).astype(float)

    # Duplikasi array a ke array u
    for i in range(n):
        for j in range(n):
            u[i, j] = a[i, j]

    # Faktorisasi LU
    for j in range(n):
        for i in range(j+1, n):
            l[i, j] = u[i, j] / u[j, j]
            u[i, j:n] = u[i, j:n] - l[i, j] * u[j, j:n]

    # Menyelesaikan ly = b
    y = gauss_elimination(l, b)

    # Menyelesaikan ux = y
    x = gauss_elimination(u, y)

    return x

### Latihan LU Decomposition

In [5]:
# Nomor 1
a3 = [[4, 3, -1], [-2, -4, 5], [1, 2, 6]]
b3 = [9, 2, 16]

x3 = lu_decomposition(np.array(a3), np.array(b3))
print(f"a = {a3}\nb = {b3}\nx = {x3}")

a = [[4, 3, -1], [-2, -4, 5], [1, 2, 6]]
b = [9, 2, 16]
x = [1.97941176 0.98823529 1.88235294]


In [7]:
# Nomor 2
a4 = [[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, -2, 3, -1]]
b4 = [4, 1, -3, 4]

x4 = lu_decomposition(np.array(a4), np.array(b4))
print(f"a = {a4}\nb = {b4}\nx = {x4}")

a = [[1, 1, 0, 3], [2, 1, -1, 1], [3, -1, -1, 2], [-1, -2, 3, -1]]
b = [4, 1, -3, 4]
x = [0.88172043 2.53763441 3.49462366 0.19354839]


## Cholesky Decomposition

In [34]:
def cholesky_factor(a):
    n = len(a)
    l = np.zeros_like(a).astype(float)

    # Mengcopy isi matriks a ke matriks l
    for i in range(n):
        for j in range(n):
            l[i, j] = a[i, j]

    for j in range(n):

        # Memastikan jika elemen matriks diagonal utama
        try:
            l[j, j] = math.sqrt(l[j, j] - np.dot(l[j, 0:j], l[j, 0:j]))
        except ValueError:
            print("Matriks tidak bisa diselesaikan dengan Cholesky Decomposition")
            return l
        
        # Melakukan forward-substitution matriks l
        for i in range(j+1, n):
            sum_term = np.dot(l[i, 0:j], l[j, 0:j])
            l[i, j] = (l[i, j] - sum_term) / l[j, j]

    # Membuat matriks l menjadi matriks segitiga bawah
    for j in range(1, n):
        l[0:j, j] = 0.0

    return l

Resolve Cholesky Sol!!!

In [38]:
def cholesky_sol(l, b):
    n = len(b)
    y = np.zeros(n).astype(float)
    x = np.zeros(n).astype(float)

    # ly = b, dengan forward-substitution
    y[0] = b[0]
    for j in range(1, n):
        sum_term = np.dot(l[j, 0:n], y[0:n])
        # sum_term = np.dot(l[j, 0:j], y[0:j])
        y[j] = (b[j] - sum_term)/l[j, j]
    
    # print("Y = ", y)
    
    # u = l_transpose
    # (l_transpose)x = y
    # lx = y, dengan backward-substitution
    for j in range(n-1, -1, -1):
        sum_term = np.dot(l[j, j+1:n], x[j+1:n])
        # sum_term = np.dot(l[j+1:n, j], x[j+1:n])
        x[j] = (y[j] - sum_term) / l[j, j]
    
    return x

In [39]:
def cholesky(a, b):
    l = cholesky_factor(a)
    x = cholesky_sol(l, b)
    return x

### Latihan Cholesky Decomposition

In [40]:
# Tentukan faktor Cholesky
a5 = [[1, 3, 5], [3, 13, 23], [5, 23, 42]]
a6 = [[4, 10, 8], [10, 26, 26], [8, 26, 61]]
b6 = [44, 128, 214]

faktor_cholesky_a5 = cholesky_factor(np.array(a5))
solusi_a6 = cholesky(np.array(a6), np.array(b6))

print(f"a = {a5}\nFaktor Cholesky = \n{faktor_cholesky_a5}")

# Contoh soal
print("Contoh penggunaan Cholesky:")
print(f"a = {a6}\nSolusi = \n{solusi_a6}")


a = [[1, 3, 5], [3, 13, 23], [5, 23, 42]]
Faktor Cholesky = 
[[1. 0. 0.]
 [3. 2. 0.]
 [5. 4. 1.]]
Contoh penggunaan Cholesky:
a = [[4, 10, 8], [10, 26, 26], [8, 26, 61]]
Solusi = 
[ 22.         -92.          65.55555556]
